<?php

declare(strict_types=1);

return [
    'snes' => [
        'name'            => 'Super Nintendo',
        'brand'           => 'Nintendo',
        'folder'          => 'snes',
        'subfolders'      => ['bios'],
        'icon'            => '/images/consoles/Nintendo - Super Nintendo Entertainment System.png',
        'file_icon'       => '/images/consoles/Nintendo - Super Nintendo Entertainment System-content.png',
        'file_extensions' => ['smc', 'sfc', 'fig', 'swc', 'bs'],
        'bios_extensions' => ['rom'],
        'exclude_files'   => [],
    ],
    'ps2' => [
        'name'            => 'PlayStation 2',
        'brand'           => 'Sony',
        'folder'          => 'ps2',
        'subfolders'      => ['DVD', 'CD', 'BIOS'],
        'icon'            => '/images/consoles/Sony - PlayStation 2.png',
        'file_icon'       => '/images/consoles/Sony - PlayStation 2-content.png',
        'file_extensions' => ['iso', 'bin', 'img', 'mdf', 'nrg'],
        'bios_extensions' => ['bin'],
        'exclude_files'   => [],
    ],
    'ps3' => [
        'name'            => 'PlayStation 3',
        'brand'           => 'Sony',
        'folder'          => 'ps3',
        'subfolders'      => ['bios'],
        'icon'            => '/images/consoles/Sony - PlayStation 3.png',
        'file_icon'       => '/images/consoles/Sony - PlayStation 3-content.png',
        'file_extensions' => ['pkg', 'iso', 'ps3'],
        'bios_extensions' => ['bin', 'pup'],
        'exclude_files'   => [],
    ],
    'gc' => [
        'name'            => 'GameCube',
        'brand'           => 'Nintendo',
        'folder'          => 'gc',
        'subfolders'      => ['bios'],
        'icon'            => '/images/consoles/Nintendo - GameCube.png',
        'file_icon'       => '/images/consoles/Nintendo - GameCube-content.png',
        'file_extensions' => ['iso', 'gcm', 'ciso', 'gcz', 'nkit.iso'],
        'bios_extensions' => ['bin'],
        'exclude_files'   => [],
    ],
    'wii' => [
        'name'            => 'Wii',
        'brand'           => 'Nintendo',
        'folder'          => 'wii',
        'subfolders'      => ['bios'],
        'icon'            => '/images/consoles/Nintendo - Wii.png',
        'file_icon'       => '/images/consoles/Nintendo - Wii-content.png',
        'file_extensions' => ['iso', 'wbfs', 'wad', 'dol'],
        'bios_extensions' => ['bin'],
        'exclude_files'   => [],
    ],
    'xbox' => [
        'name'            => 'Xbox',
        'brand'           => 'Microsoft',
        'folder'          => 'xbox',
        'subfolders'      => ['bios'],
        'icon'            => '/images/consoles/Microsoft - Xbox.png',
        'file_icon'       => '/images/consoles/Microsoft - Xbox-content.png',
        'file_extensions' => ['iso', 'xbe'],
        'bios_extensions' => ['bin', 'rom'],
        'exclude_files'   => [],
    ],
    'dreamcast' => [
        'name'            => 'Dreamcast',
        'brand'           => 'Sega',
        'folder'          => 'dreamcast',
        'subfolders'      => ['bios'],
        'icon'            => '/images/consoles/Sega - Dreamcast.png',
        'file_icon'       => '/images/consoles/Sega - Dreamcast-content.png',
        'file_extensions' => ['cdi', 'gdi', 'chd', 'iso'],
        'bios_extensions' => ['bin'],
        'exclude_files'   => [],
    ],
];
