<?php

declare(strict_types=1);

// screenscraper_id maps our console key to ScreenScraper's "systemeid" query
// parameter. Values from https://www.screenscraper.fr/api2/systemesListe.php —
// a console without an id here will return "Console not mapped to ScreenScraper"
// from the Identify endpoint.

return [
    'snes' => [
        'name'             => 'Super Nintendo',
        'brand'            => 'Nintendo',
        'folder'           => 'snes',
        'icon'             => '/images/consoles/Nintendo - Super Nintendo Entertainment System.png',
        'file_icon'        => '/images/consoles/Nintendo - Super Nintendo Entertainment System-content.png',
        'file_extensions'  => ['smc', 'sfc', 'fig', 'swc', 'bs'],
        'bios_extensions'  => ['rom'],
        'exclude_files'    => [],
        'screenscraper_id' => 4,
        'cover_aspect'     => '2/3',
        'cover_height'     => 280,
    ],
    'ps2' => [
        'name'             => 'PlayStation 2',
        'brand'            => 'Sony',
        'folder'           => 'ps2',
        'icon'             => '/images/consoles/Sony - PlayStation 2.png',
        'file_icon'        => '/images/consoles/Sony - PlayStation 2-content.png',
        'file_extensions'  => ['iso', 'bin', 'img', 'mdf', 'nrg'],
        'bios_extensions'  => ['bin'],
        'exclude_files'    => [],
        'screenscraper_id' => 58,
        'cover_aspect'     => '5/7',
        'cover_height'     => 280,
    ],
    'ps3' => [
        'name'             => 'PlayStation 3',
        'brand'            => 'Sony',
        'folder'           => 'ps3',
        'icon'             => '/images/consoles/Sony - PlayStation 3.png',
        'file_icon'        => '/images/consoles/Sony - PlayStation 3-content.png',
        'file_extensions'  => ['pkg', 'iso', 'ps3'],
        'bios_extensions'  => ['bin', 'pup'],
        'exclude_files'    => [],
        'screenscraper_id' => 57,
        'cover_aspect'     => '5/7',
        'cover_height'     => 280,
    ],
    'gc' => [
        'name'             => 'GameCube',
        'brand'            => 'Nintendo',
        'folder'           => 'gc',
        'icon'             => '/images/consoles/Nintendo - GameCube.png',
        'file_icon'        => '/images/consoles/Nintendo - GameCube-content.png',
        'file_extensions'  => ['iso', 'gcm', 'ciso', 'gcz', 'nkit.iso', 'rvz'],
        'bios_extensions'  => ['bin'],
        'exclude_files'    => [],
        'screenscraper_id' => 13,
        'cover_aspect'     => '5/7',
        'cover_height'     => 280,
    ],
    'wii' => [
        'name'             => 'Wii',
        'brand'            => 'Nintendo',
        'folder'           => 'wii',
        'icon'             => '/images/consoles/Nintendo - Wii.png',
        'file_icon'        => '/images/consoles/Nintendo - Wii-content.png',
        'file_extensions'  => ['iso', 'wbfs', 'wad', 'dol'],
        'bios_extensions'  => ['bin'],
        'exclude_files'    => [],
        'screenscraper_id' => 16,
        'cover_aspect'     => '5/7',
        'cover_height'     => 280,
    ],
    'xbox' => [
        'name'             => 'Xbox',
        'brand'            => 'Microsoft',
        'folder'           => 'xbox',
        'icon'             => '/images/consoles/Microsoft - Xbox.png',
        'file_icon'        => '/images/consoles/Microsoft - Xbox-content.png',
        'file_extensions'  => ['iso', 'xbe', 'xiso'],
        'bios_extensions'  => ['bin', 'rom'],
        'exclude_files'    => [],
        'screenscraper_id' => 32,
        'cover_aspect'     => '5/7',
        'cover_height'     => 280,
    ],
    'dreamcast' => [
        'name'             => 'Dreamcast',
        'brand'            => 'Sega',
        'folder'           => 'dreamcast',
        'icon'             => '/images/consoles/Sega - Dreamcast.png',
        'file_icon'        => '/images/consoles/Sega - Dreamcast-content.png',
        'file_extensions'  => ['cdi', 'gdi', 'chd', 'iso'],
        'bios_extensions'  => ['bin'],
        'exclude_files'    => [],
        'screenscraper_id' => 23,
        'cover_aspect'     => '7/8',
        'cover_height'     => 260,
    ],
    'gb' => [
        'name'             => 'Game Boy',
        'brand'            => 'Nintendo',
        'folder'           => 'gb',
        'icon'             => '/images/consoles/Nintendo - Game Boy.png',
        'file_icon'        => '/images/consoles/Nintendo - Game Boy-content.png',
        'file_extensions'  => ['gb', 'gbc', 'sgb'],
        'bios_extensions'  => ['bin'],
        'exclude_files'    => [],
        'screenscraper_id' => 9,
        'cover_aspect'     => '5/7',
        'cover_height'     => 260,
    ],
    'gbc' => [
        'name'             => 'Game Boy Color',
        'brand'            => 'Nintendo',
        'folder'           => 'gbc',
        'icon'             => '/images/consoles/Nintendo - Game Boy Color.png',
        'file_icon'        => '/images/consoles/Nintendo - Game Boy Color-content.png',
        'file_extensions'  => ['gbc', 'gb', 'sgb'],
        'bios_extensions'  => ['bin'],
        'exclude_files'    => [],
        'screenscraper_id' => 10,
        'cover_aspect'     => '5/7',
        'cover_height'     => 260,
    ],
    'gba' => [
        'name'             => 'Game Boy Advance',
        'brand'            => 'Nintendo',
        'folder'           => 'gba',
        'icon'             => '/images/consoles/Nintendo - Game Boy Advance.png',
        'file_icon'        => '/images/consoles/Nintendo - Game Boy Advance-content.png',
        'file_extensions'  => ['gba', 'agb', 'mb'],
        'bios_extensions'  => ['bin'],
        'exclude_files'    => [],
        'screenscraper_id' => 12,
        'cover_aspect'     => '2/3',
        'cover_height'     => 240,
    ],
    'psp' => [
        'name'             => 'PlayStation Portable',
        'brand'            => 'Sony',
        'folder'           => 'psp',
        'icon'             => '/images/consoles/Sony - PlayStation Portable.png',
        'file_icon'        => '/images/consoles/Sony - PlayStation Portable-content.png',
        'file_extensions'  => ['iso', 'cso', 'pbp', 'chd'],
        'bios_extensions'  => ['bin'],
        'exclude_files'    => [],
        'screenscraper_id' => 61,
        'cover_aspect'     => '3/5',
        'cover_height'     => 260,
    ],
    'n64' => [
        'name'             => 'Nintendo 64',
        'brand'            => 'Nintendo',
        'folder'           => 'n64',
        'icon'             => '/images/consoles/Nintendo - Nintendo 64.png',
        'file_icon'        => '/images/consoles/Nintendo - Nintendo 64-content.png',
        'file_extensions'  => ['z64', 'n64', 'v64', 'rom'],
        'bios_extensions'  => ['bin'],
        'exclude_files'    => [],
        'screenscraper_id' => 14,
        'cover_aspect'     => '8/2',
        'cover_height'     => 200,
    ],
];
